AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: '''OPTIONS,POST,GET'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''
Parameters:
  EvidentTableName:
    Type: String
    Default: Evident
    Description: (Required) The name of the new DynamoDB table you want to create
      and save to. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: Required parameter. Must be characters only. No numbers
      allowed.
Resources:
  GetAllPersonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://evidence-repo/e95e1e41c2be57aeccd0485194406755
      Handler: person.getAllPersons
      Runtime: python3.7
      Events:
        GetAllPersons:
          Type: Api
          Properties:
            Path: /getAllPersons
            Method: get
      Environment:
        Variables:
          RESOURCE_TYPE: dynamodb
          TABLE_NAME:
            Ref: EvidentTableName
          PRIMARY_KEY:
            Fn::Sub: Id
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: EvidentTableName
  GetPersonByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://evidence-repo/e95e1e41c2be57aeccd0485194406755
      Handler: person.getPersonById
      Runtime: python3.7
      Events:
        GetAllPersons:
          Type: Api
          Properties:
            Path: /getPersonById
            Method: get
Outputs:
  GetAllPersonsApi:
    Description: API Gateway endpoint URL for Prod stage for getAllPersons function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getAllPersons/
  GetAllPersonsFunction:
    Description: GetAllPersons Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetAllPersonsFunction
      - Arn
  GetAllPersonsFunctionIamRole:
    Description: Implicit IAM Role created for GetAllPersons function
    Value:
      Fn::GetAtt:
      - GetAllPersonsFunctionRole
      - Arn
  GetPersonByIdApi:
    Description: API Gateway endpoint URL for Prod stage for getPersonById function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getPersonById/
  GetPersonByIdFunction:
    Description: GetPersonById Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetPersonByIdFunction
      - Arn
  GetPersonByIdFunctionIamRole:
    Description: Implicit IAM Role created for GetPrsonById function
    Value:
      Fn::GetAtt:
      - GetPersonByIdFunctionRole
      - Arn
