AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    # Allows an application running locally on port 8080 to call this API
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Parameters:
  EvidentTableName:
    Type: String
    Default: "Evident"
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: "Required parameter. Must be characters only. No numbers allowed."

Resources:
  GetAllPersonsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: person.getAllPersons
      Runtime: python3.7
      Events:
        GetAllPersons:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getAllPersons
            Method: get
      Environment:
        Variables:
          RESOURCE_TYPE: "dynamodb"
          TABLE_NAME: !Ref EvidentTableName
          PRIMARY_KEY: !Sub Id
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EvidentTableName
  GetPersonByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: person.getPersonById
      Runtime: python3.7
      Events:
        GetAllPersons:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getPersonById
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetAllPersonsApi:
    Description: "API Gateway endpoint URL for Prod stage for getAllPersons function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getAllPersons/"
  GetAllPersonsFunction:
    Description: "GetAllPersons Lambda Function ARN"
    Value: !GetAtt GetAllPersonsFunction.Arn
  GetAllPersonsFunctionIamRole:
    Description: "Implicit IAM Role created for GetAllPersons function"
    Value: !GetAtt GetAllPersonsFunctionRole.Arn
  GetPersonByIdApi:
    Description: "API Gateway endpoint URL for Prod stage for getPersonById function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getPersonById/"
  GetPersonByIdFunction:
    Description: "GetPersonById Lambda Function ARN"
    Value: !GetAtt GetPersonByIdFunction.Arn
  GetPersonByIdFunctionIamRole:
    Description: "Implicit IAM Role created for GetPrsonById function"
    Value: !GetAtt GetPersonByIdFunctionRole.Arn
